### ISSUE TITLE
bus load monitoring

### ISSUE THREAD

**Issue by sysmax-pan** [moonglow/pcan_pro_x#14]
I noticed that the Pro doesn't have bus load monitoring, and the FD does。
I'm not sure if their（PCAN PRO and PCAN PRO FD） usb protocol is similar？and whether we can fix this problem in a similar way？

**Comment by moonglow** [comment]
Hi @sysmax-pan !

PCAN PRO/PCAN PRO FD has a different protocols and i recommends to use PRO FD version because it get latest updates firstly ( PRO version be updated too, but with much bigger latency ) and Peak windows driver for PRO FD is more optimized for high rate data via USB FS. Why you do not want to use PRO FD version instead ?

p.s: you can also implement it yourself and send me pull-request
