### ISSUE TITLE
Why not use the STM32G431 for the CAN FD firmware?

### ISSUE THREAD

**Issue by Linjieqiang** [moonglow/pcan_pro_x#3]

**Comment by moonglow** [comment]
My main goal is easy-to-make hardware, but i can't find cheap hardware board based on STM32G series. Firmware is ready to run on such hardware. All CAN FD handlers is already written and well tested. I adds CAN FD firmware ( PRO FD/ FD ) for this project because Windows driver for FD series works better on USB 2.0 FS ( it mean no frame skipping while your works with 2 channels simultaneously ).

**Comment by MarkoBursic** [comment]
Makerbase MKS Canable Pro v2.0 , It has STM32G431
