### ISSUE TITLE
Sending data lost with huge data stream

### ISSUE THREAD

**Issue by sysmax-cn** [moonglow/pcan_pro_x#7]
Recently I did a stress test for data  sending .
I find that sending data will be lost when huge data stream what comes without delay.

For pcan_cantact, I seen this code that will NACK to host when TXFIFO is full. 
(This commit : https://github.com/moonglow/pcan_cantact/commit/43533b5b4a4dc1c84cf72534f77192de33b848da)
And pcan_cantact can pass this test perfectly with this commit.

I'm not sure if their（PCAN and PCAN PRO） usb protocol is similar？and whether we can fix this problem in a similar way？

**Comment by moonglow** [comment]
Hi @sysmax-cn  !

>  I find that sending data will be lost when huge data stream what comes without delay.

Yep it known issue, but adapter will works OK for mostly all real application without synthetic tests, but if someone will do pull request with good solution, it will be nice. For two channel we can't just stop USB stream, because more slower channel with huge data stream ( why ???? ) will also slow down second active channel.

>I'm not sure if their（PCAN and PCAN PRO） usb protocol is similar

PCAN, PCAN PRO, PCAN FD(PRO FD ) has they own protocols, but my fix for pcan_cantact works on USB level not on pcan protocol level and i added it to fix an error on firmware update over UDS and so on. So it be needed to make adapter works better with real application ( i read about that issue here: [amobbs](https://amobbs.com/thread-5750363-1-1.html) )
